language: r
cache: packages
sudo: false

env:
  global:
    - NOT_CRAN=true

os:
  - linux

r:
  - release

branches:
  only: 
    - m-introduce-travis

after_success:
  - if [[ "$DO_CODECOV" == "true" ]]; then travis_wait 30 Rscript -e 'covr::codecov()'; fi